### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Butonix** [Olunuga/MediumClone#20]
Build Failed

**Comment by Butonix** [comment]
Xcode 12.1
Showing All Messages
:-1: Build input files cannot be found: '/Users/Desktop/MediumClone-master 2/MediumClone/MediumClone/Module/Home/HomeViewModel.swift', '/Users/ckatala/Desktop/MediumClone-master 2/MediumClone/MediumClone/Module/Search/HeaderView/HeaderView.swift', '/Users/ckatala/Desktop/MediumClone-master 2/MediumClone/MediumClone/Module/CommonViews/CompactStoryCell/CompactStoryCollectionViewCell.swift', '/Users/ckatala/Desktop/MediumClone-master 2/MediumClone/MediumClone/Module/CommonViews/WideStoryCell/WideStoryViewCell.swift', '/Users/ckatala/Desktop/MediumClone-master 2/MediumClone/MediumClone/Module/Create/CreateViewController.swift', '/Users/ckatala/Desktop/MediumClone-master 2/MediumClone/MediumClone/Module/Search/SuggestedCell/suggestedTableViewCell.swift', '/Users/ckatala/Desktop/MediumClone-master 2/MediumClone/MediumClone/Module/Bookmark/BookmarkViewController.swift', '/Users/ckatala/Desktop/MediumClone-master 2/MediumClone/MediumClone/Module/Search/SearchViewController.swift', '/Users/ckatala/Desktop/MediumClone-master 2/MediumClone/MediumClone/Module/Activities/ActivityCell.swift', '/Users/ckatala/Desktop/MediumClone-master 2/MediumClone/MediumClone/Module/Search/SuggestedHeader/SuggestedHeaderView.swift', '/Users/ckatala/Desktop/MediumClone-master 2/MediumClone/MediumClone/Module/Profile/Cell/ProfileDetailView.swift', '/Users/ckatala/Desktop/MediumClone-master 2/MediumClone/MediumClone/Module/Profile/Sections/ProfileSectionCell.swift', '/Users/ckatala/Desktop/MediumClone-master 2/MediumClone/MediumClone/Module/Profile/Cell/ProfileDetailCell.swift', '/Users/ckatala/Desktop/MediumClone-master 2/MediumClone/MediumClone/Module/CommonViews/SwipableCell/SwipableTableViewCell.swift', '/Users/ckatala/Desktop/MediumClone-master 2/MediumClone/MediumClone/Module/Profile/ProfileReloaded.swift', '/Users/ckatala/Desktop/MediumClone-master 2/MediumClone/MediumClone/Module/Profile/ProfileViewController.swift', '/Users/ckatala/Desktop/MediumClone-master 2/MediumClone/MediumClone/Module/Activities/ActivityViewController.swift', '/Users/ckatala/Desktop/MediumClone-master 2/MediumClone/MediumClone/AppDelegate.swift', '/Users/ckatala/Desktop/MediumClone-master 2/MediumClone/MediumClone/Module/Search/ItemCell/SearchItemViewCell.swift', '/Users/ckatala/Desktop/MediumClone-master 2/MediumClone/MediumClone/Module/Home/HomeViewController.swift', '/Users/ckatala/Desktop/MediumClone-master 2/MediumClone/MediumClone/Module/Profile/Sections/LatestSectionViewController.swift'

**Comment by Butonix** [comment]
No such module 'MaterialComponents.MDCCard'

**Comment by Olunuga** [comment]
confirm you have 

>  pod 'MaterialComponents/Cards'

 in your pod file and you have run pod install.
